language: c
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - autoconf
          - automake
          - libtool
          - guile-2.0-dev
          - liblapack-dev
          - libblas-dev
          - gfortran
          - libfftw3-dev
          - libhdf5-serial-dev
          - git
      script:
        - git clone https://github.com/stevengj/libctl
        - (cd libctl && git checkout master && sh autogen.sh --prefix=$HOME/local && make && make install)
        - sh autogen.sh --enable-maintainer-mode --prefix=$HOME/local --with-libctl=$HOME/local/share/libctl GEN_CTL_IO=$HOME/local/bin/gen-ctl-io CPPFLAGS=-I$HOME/local/include LDFLAGS=-L$HOME/local/lib
        - make && make check && make install
    - os: osx
      install:
        - brew tap homebrew/science
        - brew update
        - brew cask uninstall oclint # travis issue #8826
        - brew install guile fftw lapack
      script:
        - git clone https://github.com/stevengj/libctl
        - (cd libctl && git checkout master && sh autogen.sh --prefix=$HOME/local && make && make install)
        - sh autogen.sh --prefix=$HOME/local --with-hermitian-eps
        - make && make check && make install
        - ./configure --prefix=$HOME/local --with-inv-symmetry
        - make && make check && make install
